-- ============================================================
-- RJ Studio - Booking system schema
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

create extension if not exists btree_gist;

-- ------------------------------------------------------------
-- Studios
-- ------------------------------------------------------------
create table if not exists public.studios (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text,
  size_label text,
  capacity_label text,
  price_peak_mad integer not null check (price_peak_mad >= 0),
  price_offpeak_mad integer not null check (price_offpeak_mad >= 0),
  image_url text,
  gallery_urls text[] not null default '{}',
  features text[] not null default '{}',
  popular boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Settings (single row, id = 1)
-- opening_hours: JSON object keyed by weekday (0 = Sunday .. 6 = Saturday),
--   value = {"open": "08:00", "close": "22:00"} or null when closed.
-- peak_windows: JSON array of {"days": [1,2,3,4,5], "start": "17:00", "end": "22:00"}
-- ------------------------------------------------------------
create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  opening_hours jsonb not null,
  peak_windows jsonb not null,
  paypal_email text,
  paypal_link text,
  bank_details text,
  confirmation_deadline_hours integer not null default 48,
  reminder_hours_before integer not null default 24,
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Bookings
-- Times are stored as the studio's local time (Africa/Casablanca):
--   date + start_minutes (minutes from midnight) + duration_minutes.
-- ------------------------------------------------------------
create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  studio_id bigint not null references public.studios (id),
  date date not null,
  start_minutes integer not null check (start_minutes >= 0 and start_minutes < 1440),
  duration_minutes integer not null check (duration_minutes >= 60 and duration_minutes % 30 = 0),
  total_price_mad numeric(10, 2) not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  note text,
  payment_method text not null check (payment_method in ('paypal', 'virement', 'cash')),
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'cancelled', 'expired', 'completed')),
  payment_deadline timestamptz not null,
  admin_note text,
  client_reminder_sent_at timestamptz,
  admin_reminder_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bookings_studio_date_idx on public.bookings (studio_id, date);
create index if not exists bookings_status_idx on public.bookings (status);
create index if not exists bookings_created_at_idx on public.bookings (created_at desc);

-- Prevent double-booking at the database level: two active bookings
-- (pending or confirmed) can never overlap for the same studio and date.
alter table public.bookings drop constraint if exists bookings_no_overlap;
alter table public.bookings add constraint bookings_no_overlap
  exclude using gist (
    studio_id with =,
    date with =,
    int4range(start_minutes, start_minutes + duration_minutes) with &&
  )
  where (status in ('pending', 'confirmed'));

-- ------------------------------------------------------------
-- Row Level Security
-- Public (anon) can read active studios and settings.
-- Bookings are only accessed server-side with the service role key
-- (service role bypasses RLS), so no anon policies are defined.
-- ------------------------------------------------------------
alter table public.studios enable row level security;
alter table public.settings enable row level security;
alter table public.bookings enable row level security;

drop policy if exists "Public can read active studios" on public.studios;
create policy "Public can read active studios"
  on public.studios for select
  using (active = true);

drop policy if exists "Public can read settings" on public.settings;
create policy "Public can read settings"
  on public.settings for select
  using (true);

-- Promo codes (admin/service role only — no public policies)
create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric(10,2) not null check (discount_value > 0),
  min_amount_mad numeric(10,2),
  max_uses integer check (max_uses is null or max_uses > 0),
  uses_count integer not null default 0 check (uses_count >= 0),
  valid_from timestamptz,
  valid_until timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists promo_codes_code_idx on public.promo_codes (code);
alter table public.promo_codes enable row level security;

alter table public.bookings
  add column if not exists promo_code text,
  add column if not exists subtotal_price_mad numeric(10,2),
  add column if not exists discount_amount_mad numeric(10,2) default 0;

alter table public.bookings
  add column if not exists course_type text not null default 'group'
    check (course_type in ('group', 'private'));

alter table public.bookings
  add column if not exists regular_course_count integer
    check (regular_course_count is null or regular_course_count >= 1);

alter table public.bookings
  add column if not exists package_group_id uuid;

alter table public.bookings
  add column if not exists package_index integer
    check (package_index is null or package_index >= 1);

create index if not exists bookings_package_group_id_idx
  on public.bookings (package_group_id)
  where package_group_id is not null;

-- Public availability: time slots only (no client PII)
create or replace function public.get_busy_slots(p_studio_id int, p_date date)
returns table (start_minutes int, duration_minutes int)
language sql
stable
security definer
set search_path = public
as $$
  select b.start_minutes, b.duration_minutes
  from public.bookings b
  where b.studio_id = p_studio_id
    and b.date = p_date
    and b.status in ('pending', 'confirmed');
$$;

revoke all on function public.get_busy_slots(int, date) from public;
grant execute on function public.get_busy_slots(int, date) to anon, authenticated, service_role;

-- ------------------------------------------------------------
-- Seed data
-- ------------------------------------------------------------
insert into public.studios
  (name, subtitle, size_label, capacity_label, price_peak_mad, price_offpeak_mad, image_url, features, popular, active, sort_order)
values
  (
    'Studio 1',
    'Idéal pour les groupes et les ateliers',
    'Grand - 49m²',
    '10-16 personnes',
    400, 300,
    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    array['Système son Bluetooth', 'Climatisation', 'Grand miroirs', 'Forfait 10h + 1h gratuite'],
    true, true, 1
  ),
  (
    'Studio 2',
    'Parfait pour les cours de danse ou fitness en groupe',
    'Moyen - 34m²',
    '7-12 personnes',
    300, 200,
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    array['Système son Bluetooth', 'Climatisation', 'Grand miroirs', 'Forfait 10h + 1h gratuite'],
    false, true, 2
  ),
  (
    'Studio 3',
    'Parfait pour les cours privés, répétitions ou petits groupes',
    'Moyen - 30m²',
    '6-10 personnes',
    250, 150,
    'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800&q=80',
    array['Système son Bluetooth', 'Climatisation', 'Grand miroirs', 'Forfait 10h + 1h gratuite'],
    false, true, 3
  )
on conflict do nothing;

-- Default: open every day 08:00-22:00.
-- Peak hours ("heures pleines"): weekdays 17:00-22:00; weekends 08:00-09:00 & 11:00-22:00.
-- Weekend off-peak ("heures creuses"): 09:00-11:00 Saturday & Sunday. Editable in admin.
insert into public.settings (id, opening_hours, peak_windows, paypal_email, paypal_link, bank_details, confirmation_deadline_hours, reminder_hours_before)
values (
  1,
  '{
    "0": {"open": "08:00", "close": "22:00"},
    "1": {"open": "08:00", "close": "22:00"},
    "2": {"open": "08:00", "close": "22:00"},
    "3": {"open": "08:00", "close": "22:00"},
    "4": {"open": "08:00", "close": "22:00"},
    "5": {"open": "08:00", "close": "22:00"},
    "6": {"open": "08:00", "close": "22:00"}
  }'::jsonb,
  '[
    {"days": [1, 2, 3, 4, 5], "start": "17:00", "end": "22:00"},
    {"days": [0, 6], "start": "08:00", "end": "09:00"},
    {"days": [0, 6], "start": "11:00", "end": "22:00"}
  ]'::jsonb,
  'contact@studiorj.ma',
  null,
  'Titulaire : RJ Studio
Banque : (à compléter)
RIB : (à compléter)
IBAN : (à compléter)',
  48,
  24
)
on conflict (id) do nothing;
