-- Promo codes for booking discounts. Run in Supabase SQL Editor.

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric(10,2) not null check (discount_value > 0),
  min_amount_mad numeric(10,2),
  max_uses integer check (max_uses is null or max_uses > 0),
  uses_count integer not null default 0 check (uses_count >= 0),
  valid_from timestamptz,
  valid_until timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists promo_codes_code_idx on public.promo_codes (code);
create index if not exists promo_codes_active_idx on public.promo_codes (active);

alter table public.promo_codes enable row level security;

alter table public.bookings
  add column if not exists promo_code text,
  add column if not exists subtotal_price_mad numeric(10,2),
  add column if not exists discount_amount_mad numeric(10,2) default 0;
